### ISSUE TITLE
Remove TryFrom and TryInto when Rust std trait is stablized

### ISSUE THREAD

**Issue by sorpaas** [paritytech/parity-common#103]
rel https://github.com/paritytech/parity-common/pull/97#discussion_r251072263

**Comment by niklasad1** [comment]
`TryFrom` and `TryInto` will be stabilized in [Rust 1.34](https://github.com/XAMPPRocky/rust/blob/master/RELEASES.md#stabilized-apis)

**Comment by ordian** [comment]
Closed by #127.
