### ISSUE TITLE
The Cargo.toml of `uint` crate miss features?

### ISSUE THREAD

**Issue by koushiro** [paritytech/parity-common#112]
And `uint` crate seems to be missing the `quickcheck` and `heapsize` features in Cargo.toml, however, the `heapsize` and `quickcheck` dependencies is optional.

**Comment by Robbepop** [comment]
As far as I know we wanted to get rid of `heapsize` feature in our crates. Can't tell what happened to the `quickcheck` feature though.

**Comment by bkchr** [comment]
These features are still available, see https://github.com/rust-lang/cargo/issues/4911
