### ISSUE TITLE
[parity-crypto] doc comments and updating some dependencies

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/parity-common#119]
I've been working with @tomusdrw on adding pure Rust feature switch to `ethsign`, which inevitably lead to developing a drop-in replacement for `parity-crypto` that does not depend on `ring` or other `C` dependencies (those are a massive pain in the neck when compiling to Android/iOS).

This is quite a chore, and it's doubly troublesome as the crate lacks documentation ([which came up during the PR review](https://github.com/tomusdrw/ethsign/pull/16)).

Also while porting stuff, I found that the `scrypt` algo used is using the deprecated `rust-crypto` crate, instead of the standalone `scrypt` crate. It might be worth upgrading that one, along with switching some of the `ring` stuff to pure Rust alternatives in cases where there performance regression for doing so is either tolerable or not very relevant (`aes` would be a good example).

I think having `ring` behind a feature flag, disabling which would also disable all parts of `parity-crypto` that depend on it, leaving only Rust dependencies would be ideal for long term maintainability.

**Comment by ordian** [comment]
@maciejhirsz can this be closed now? (cf #144)

**Comment by maciejhirsz** [comment]
@ordian I think so!
