### ISSUE TITLE
Support `TryFrom/TryInto` for uint types

### ISSUE THREAD

**Issue by shaopengw** [paritytech/parity-common#131]
uint types has `as_u32/as_u64/as_u128` functions, but they would panic if overflow. It would be helpful if `TryFrom/TryInto` is supported, so that caller can decide what to do (for instance saturating) instead of panic.

**Comment by dvdplm** [comment]
@shaopengw are you interested in contributing a patch? :)

**Comment by shaopengw** [comment]
@dvdplm Sure, I'm happy to work on it. :]
