### ISSUE TITLE
Migrate all crates to 2018 edition

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-common#143]
cc https://github.com/paritytech/parity-common/pull/140#discussion_r282640333

- [x] ethbloom
- [x] ethereum-types
- [x] fixed-hash
- [x] keccak-hash
- [x] kvdb
- [x] kvdb-memorydb
- [x] kvdb-rocksdb
- [x] parity-bytes
- [x] parity-crypto
- [x] parity-path
- [x] parity-util-mem
- [x] plain_hasher
- [ ] primitive-types
- [x] trace-time
- [x] transaction-pool
- [x] triehash
- [x] uint
- [ ] impl-codec (in primitive-types/impls)
- [ ] impl-rlp (in primitive-types/impls)
- [x] impl-serde (in primitive-types/impls)

**Comment by zrzka** [comment]
`transaction-pool` was already migrated to 2018 edition in #170.
