### ISSUE TITLE
expected `&[u8]`, found ElasticArray32<u8>

### ISSUE THREAD

**Issue by bradyjoestar** [paritytech/parity-common#150]
rustc version: rustc 1.34.1 (fc50f328b 2019-04-24)

I'm trying to use kvdb-memorydb but it shows the above error : `expected `&[u8]`, found ElasticArray32<u8>`  in the following code:
https://github.com/paritytech/parity-common/blob/e20825076b179defdf5bb0e5dd7847aecf047571/kvdb/src/lib.rs#L55-L62

Could you tell me how to fix it, Thanks!

**Comment by ordian** [comment]
> I'm trying to use kvdb-memorydb 

Could you show the code you're trying to run?

**Comment by bradyjoestar** [comment]
sorry, I am wrong. I haven't write any code and `ide` show me this:
![screenshop](https://upload-images.jianshu.io/upload_images/6907217-13a412c0d9a030cc.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by ordian** [comment]
ah, I see, that's a bug in intellij-rust plugin

**Comment by bradyjoestar** [comment]
Thank you!@ordian
