### ISSUE TITLE
support paritybytes in #![no_std] libraries

### ISSUE THREAD

**Issue by bradyjoestar** [paritytech/parity-common#153]
In #![no_std] libraries, we need to use `alloc::vec::Vec` instead of  `std::vec::Vec`, like `bitvec` did.
https://github.com/myrrlyn/bitvec

My pleasure to create a pr about it. :)

**Comment by dvdplm** [comment]
> My pleasure to create a pr about it. :)

By all means yes. Shout if you need anything from us. :)

**Comment by bradyjoestar** [comment]
Sure!
