### ISSUE TITLE
[parity-util-mem] Add more tests

### ISSUE THREAD

**Issue by dvdplm** [paritytech/parity-common#174]
There's a single test and it is not currently run by travis (or by `cargo test`). Sort out the features and make sure the test runs.

Adding tests would be good too.

**Comment by ordian** [comment]
The test is run, see e.g. https://travis-ci.org/paritytech/parity-common/jobs/576744893#L1194. I agree with the need of more tests though.

**Comment by Xanewok** [comment]
Since https://github.com/paritytech/parity-common/pull/559 is merged and we even test with different allocators now, can we close this?
