### ISSUE TITLE
[parity-util-mem] add support for mimalloc

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-common#180]
https://github.com/microsoft/mimalloc seems to be a better choice than jemalloc (time- and memory-wise). We would probably need a low-level rust crate wrapping its C API first, like jemalloc-sys.

**Comment by ordian** [comment]
There are rust bindings https://github.com/gnzlbg/mimallocator already

**Comment by cheme** [comment]
Note that mimallocator-sys does not include 'mi_usable_size' that could be use for malloc_size_of, but that is not a big change to do.

**Comment by dvdplm** [comment]
> mimallocator-sys does not include 'mi_usable_size'

Maybe file an issue with them?

**Comment by cheme** [comment]
Not sure until we use it actually (or not).
The change is a single line addition but still.
```
diff --git a/mimalloc-sys/src/lib.rs b/mimalloc-sys/src/lib.rs
index 43401ae..b86c058 100644
--- a/mimalloc-sys/src/lib.rs
+++ b/mimalloc-sys/src/lib.rs
@@ -12,5 +12,6 @@ extern "C" {
     pub fn mi_realloc(p: *mut c_void, newsize: size_t) -> *mut c_void;
     pub fn mi_realloc_aligned(p: *mut c_void, newsize: size_t, alignment: size_t) -> *mut c_void;
 
+    pub fn mi_usable_size(p: *mut c_void) -> size_t;
     pub fn mi_free(p: *mut c_void);
 }
```

**Comment by dvdplm** [comment]
> Not sure until we use it actually (or not).

I'm sure they'd be happy to consider a PR. Looks like it's a simple oversight on their part. :)
