### ISSUE TITLE
Calculate contract address from `from` address + `nonce`

### ISSUE THREAD

**Issue by thomaseizinger** [paritytech/parity-common#186]
The address of a contract can be deterministically calculated from the `from` address and the `nonce` of the transaction.

Currently, we implemented this code ourselves in our codebase, however since it is generally useful, we would like to contribute it back. Which of the crates in this repository would be best for this functionality?

**Comment by dvdplm** [comment]
Good question actually. What does the (hypothetical?) API look like (to get an idea of the use case)? I'd say it probably belongs in `parity-ethereum` tbh, but possibly in `ethereum-types` too.

cc @ordian thoughts?

**Comment by thomaseizinger** [comment]
It is a simple, pure function with the signature:
(address, nonce) -> address

**Comment by ordian** [comment]
@thomaseizinger are you referring to [this](https://github.com/paritytech/parity-ethereum/blob/9d9e2b43f29475aad3e4d29872d72c6610edef22/ethcore/src/executive.rs#L57-L84) code?

I don't have a strong opinion on that, but the last thing we need is to [copy npm community](https://twitter.com/ArvidGerstmann/status/1140550749207900160/photo/1) :sweat_smile:

**Comment by thomaseizinger** [comment]
> @thomaseizinger are you referring to this code?

Not quite. I am actually referring to the algorithm defined in the yellow paper which, to my knowledge, only depends on `from` address and `nonce`, not the `code` of the contract.

That linked tweet is hilarious but totally not what I had in mind :)
It is just, if the code doesn't quite fit anywhere, maybe it belongs in its own crate.

In particular, it is a piece of code you don't want to write/maintain yourself because it is part of the spec and hence, you should be able to import it from somewhere. `parity-ethereum` is the whole node right? Also not quite something I want to depend on just for this function :)

**Comment by thomaseizinger** [comment]
This is what we currently do:

https://github.com/comit-network/comit-rs/blob/master/vendor/ethereum_support/src/contract_address.rs

**Comment by ordian** [comment]
> parity-ethereum is the whole node right? 

it's the full node, [light node](https://wiki.parity.io/Light-Client.html), it also supports [pluggable consensus](https://wiki.parity.io/Pluggable-Consensus.html) and [contracts in wasm](https://github.com/paritytech/pwasm-tutorial).

> in particular, it is a piece of code you don't want to write/maintain yourself because it is part of the spec and hence, you should be able to import it from somewhere.

[EIP-1014's CREATE2 opcode](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1014.md) is now also part of the spec, so we have to support it.

```rust
/// Specifies how an address is calculated for a new contract.
#[derive(Copy, Clone, PartialEq, Eq, Debug, Hash)]
pub enum CreateContractAddress {
	/// Address is calculated from sender and nonce. pWASM `create` scheme.
	FromSenderAndNonce,
	/// Address is calculated from sender, salt and code hash. pWASM `create2` scheme and EIP-1014 CREATE2 scheme.
	FromSenderSaltAndCodeHash(H256),
	/// Address is calculated from code hash and sender. Used by pwasm create ext.
	FromSenderAndCodeHash,
}
```

We could extract the first two variants in a crate, WDYT?

**Comment by thomaseizinger** [comment]
> We could extract the first two variants in a crate, WDYT?
