### ISSUE TITLE
Add AsRef<[u64]> trait + impl to all U-type integers

### ISSUE THREAD

**Issue by fubuloubu** [paritytech/parity-common#195]
H-types  (such as H256) created through the `construct_fixed_hash` macro implement the `AsRef<[u8]>` trait to gain access to the internal data, but U-types (such as U256) does not implement a similar trait (such as `AsRef<[u64]>`) to gain access to their internal data.

Please note, there seems to be an inconsistency in how `uint` and `hash` use `AsRef` trait, which may be the source of this issue
https://github.com/paritytech/parity-common/blob/cd0fe159c8cb26b1c855e9f110aecd4bf4a40a24/fixed-hash/src/hash.rs#L101-L106

https://github.com/paritytech/parity-common/blob/cd0fe159c8cb26b1c855e9f110aecd4bf4a40a24/uint/src/uint.rs#L427-L431

**Comment by dvdplm** [comment]
Thank you for the report, that does indeed look odd. PR very welcome! :)

**Comment by fubuloubu** [comment]
Sorry, edited to specify `u64` instead of `u32` as that seems to be the preferred base for all U-type integers.

I will get started on this shortly!
