### ISSUE TITLE
Where is U256?

### ISSUE THREAD

**Issue by lightclient** [paritytech/parity-common#198]
In the `uint` crate there is the follow declaration:

> Also provides commonly used U128, U256 and U512 out of the box.

I don't see any of these defined in the crate. I'm not sure I'm misunderstanding what is supposed to be provided. I would've expected to see a few `constuct_uint!  { pub struct N (N/64) }` in the repo.

**Comment by ordian** [comment]
@lightclient it seems like the `uint` docs are quite outdated, you can find these definitions in `primitive-types` crate.

**Comment by lightclient** [comment]
@ordian great, thank you!
