### ISSUE TITLE
[rlp] Rename complete_unbounded_list to finalize_unbounded_list

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-common#204]
from https://github.com/paritytech/parity-common/pull/203#discussion_r317561389:
> "complete" can be both the imperative form of the verb as in "complete your homework before dinner!" or be and adjective "a complete list of my belongings".
"finalize" does not have this ambiguity.

> In this context the ambiguity makes it unclear if the method returns an unbounded list of something that is complete, or that it takes an unbounded list and completes it.

> We can add a copy named finalize_unbounded_list and deprecate this one. In another PR.

**Comment by hugovk** [comment]
Please see PR https://github.com/paritytech/parity-common/pull/228.
