### ISSUE TITLE
impl_serde broken on latest Serde upstream

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/parity-common#207]
Found while working on <https://github.com/paritytech/substrate/pull/3457>.

**Comment by thiolliere** [comment]
I can't reproduce. I did `cargo update -p serde` and everything works fine

**Comment by DemiMarie-parity** [comment]
Nevermind.  The problem was that Substrate was using this crate in an unintended way, which lead to breakage.

**Comment by ordian** [comment]
@DemiMarie-parity is it ok to close the issue then?

**Comment by DemiMarie-parity** [comment]
@ordian yes.
