### ISSUE TITLE
Releasing new minor primitive-types

### ISSUE THREAD

**Issue by thiolliere** [paritytech/parity-common#224]
I want to release new minor release of primitive-types so it include changes in impl-codec.

Anybody against ? If none I can do it now

**Comment by ordian** [comment]
if you public new minor release of `impl-codec`, there is no need to publish `primitive-types`, since it doesn't have `Cargo.lcck`.

**Comment by thiolliere** [comment]
yes, but then if I want to use the new version of impl-codec I will have to put in my dependency and increment the minor release. (I mean if I want it to be in my Cargo.toml indeed I can do `cargo updat e-p impl-codec` but then I'm using a feature that I haven't specified using in the Cargo.toml 🤔

**Comment by ordian** [comment]
Feel free to publish new version, just make sure we haven't merged any breaking changes.

**Comment by thiolliere** [comment]
done

**Comment by dvdplm** [comment]
@thiolliere please make sure you tag the repo with the release version (maybe you did, didn't check). :)
