### ISSUE TITLE
[primitive-types] use `mem::MayubeUninit`

### ISSUE THREAD

**Issue by dvdplm** [paritytech/parity-common#233]
Stop using `std::mem::uninitialized` and switch to `mem::MaybeUninit` instead.

**Comment by ordian** [comment]
It's only used in uint binary ops https://github.com/paritytech/parity-common/blob/b0ec18dafed2d85a947d866a2ea0477ab2238a76/uint/src/uint.rs#L80

We should try to replace it with zero initialization (`let mut ret = [0u64; $n_words];`) and run the benchmarks for uint binops to see if there is a difference. If there is, switch to `MaybeUninit` then.

**Comment by Ishaan28malik** [comment]
Is this issue still Open and unassigned ?

**Comment by ordian** [comment]
@Ishaan28malik, yes, feel free to submit a PR :)

**Comment by RaitoBezarius** [comment]
I guess this can be closed?
