### ISSUE TITLE
Old description of the crate uint on crates.io

### ISSUE THREAD

**Issue by eisterman** [paritytech/parity-common#241]
The webpage of the crate [uint](https://crates.io/crates/uint) on crates.io report actually an old state of the things.
In particular the syntax for using the `construct_uint!` macro is wrong and is reported the presence in the crate of the types U128, U256, U512 if the feature `common` is enabled, but this feature is not more present, and that types are now in the crate `primitive-types`.

There's a need to update the webpage, or directly delete the text content and insert a direct link to the README.md in this repo, so that misunderstandings no longer occur.

I've already submitted a pull request for fixing the out-of-date README.md of `uint`.

**Comment by ordian** [comment]
Resolved in #240.
