### ISSUE TITLE
Square root of U256?

### ISSUE THREAD

**Issue by WyseNynja** [paritytech/parity-common#252]
How should I calculate the square root of a U256?

```
no method named `sqrt` found for type `primitive_types::U256` in the current scope

method not found in `primitive_types::U256`
```

**Comment by ordian** [comment]
For integer square root one could use [Newton's method](https://en.wikipedia.org/wiki/Integer_square_root#Using_only_integer_division). The tricky part is setting the initial guess right, you could see how [num-bigint does that](https://github.com/rust-num/num-bigint/blob/fc6986508013be9a472858d837c20cacfbaf7a88/src/biguint.rs#L1448-L1480).

**Comment by WyseNynja** [comment]
Thank you.

I ended up reading more of synthetix's ArbRewarder.sol and they had this function:

```
    function sqrt(uint x) private pure returns (uint y) {
        uint z = (x + 1) / 2;
        y = x;
        while (z < y) {
            y = z;
            z = (x / z + z) / 2;
        }
    }
```

So I wrote this rust:

```
fn integer_sqrt(x: U256) -> U256 {
    let two: U256 = 2.into();

    let mut z: U256 = (x + U256::one()) / two;

    let mut y = x;

    while z < y {
        y = z;
        z = (x / z + z) / two;
    }

    z
}
```

**Comment by ordian** [comment]
@WyseNynja yep, that's Newton's method with the initial guess set to `(x + 1) / 2`, not the most efficient one, but simple enough. One simple optimization you can apply is use right shift instead of division by 2, e.g. `(x + U256::one()) >> 1`
