### ISSUE TITLE
Potential infinite recursion in `rlp::stream::BasicEncoder::encode_iter`

### ISSUE THREAD

**Issue by reuvenpo** [paritytech/parity-common#261]
Potential infinite recursion in `rlp::stream::BasicEncoder::encode_iter` when passing in an `IntoIter` whose `IntoIter::Iter::size_hint` method returns a value with `lower != upper` size bounds (and the `upper` is not `None`.)

for example, `(5, Some(6))`.

[see code here](https://github.com/paritytech/parity-common/blob/a9aa5893d354779af4ae9591bc93686cb1d72268/rlp/src/stream.rs#L407)

I should point out that this is not an issue for vector and slice iterators, which return their real length as both bounds of the size hint.

**Comment by ordian** [comment]
Hey, thanks for opening the issue for discussion. The code you linked will call `encode_iter` on a `Vec` https://github.com/paritytech/parity-common/blob/a9aa5893d354779af4ae9591bc93686cb1d72268/rlp/src/stream.rs#L406-L407 so I don't see how it could recurse infinitely.

**Comment by reuvenpo** [comment]
Oh that's actually very true. I literally said it myself - "this is not an issue for vector and slice iterators".
Sorry for opening this issue, it can be closed.
