### ISSUE TITLE
[fixed-hash] Tests produce lot dead_code of warnings

### ISSUE THREAD

**Issue by zrzka** [paritytech/parity-common#265]
Take [this Travis CI job](https://travis-ci.org/paritytech/parity-common/jobs/614193654?utm_medium=notification&utm_source=github_status) as an example.

* `dead_code` warnings - 2234 lines
  * [Lines 547-1358](https://travis-ci.org/paritytech/parity-common/jobs/614193654#L547-L1358) - 811 lines
  * [Lines 2027-2838](https://travis-ci.org/paritytech/parity-common/jobs/614193654#L2027-L2838) - 811 lines
  * [Lines 2895-3507](https://travis-ci.org/paritytech/parity-common/jobs/614193654#L2895-L3507) - 612 lines
* The whole job log - 4093 lines

55% of lines in the log are about `dead_code` warnings from the single crate.

While the green check mark is enough, it's quite hard/time consuming to scroll through the log when an error occurs.

This can be fixed in two ways:

* pragmatic approach & quick fix
  * add `#![allow(dead_code)]` to the `fixed-hash/src/tests.rs` as a first line,
* spend more time on this and try to fix it in a better way without allowing `dead_code`.

**Comment by niklasad1** [comment]
@zrzka Those warnings are not really related to the test-code in particular but related to the `macro construct_fixed_hash!` which implements a bunch of methods.

I'm not completely sure why `rustc` just warns about only the `test build` but I suspect that `rustc` can't detect that those are publicly exported or something because of the macro.

> pragmatic approach & quick fix
    - add #![allow(dead_code)] to the fixed-hash/src/tests.rs as a first line,

I suppose we could add `allow(dead_code)` for individual methods (i.e, not `#![allow(dead_code)]`) 

> spend more time on this and try to fix it in a better way without allowing dead_code.

Seems to be a `rustc` related because I expect the `macro pub` methods to not have warnings because they are exported outside the crate.

**Comment by zrzka** [comment]
@niklasad1 I checked it and the `rustc` warns about `dead_code`, because the `construct_fixed_hash!` implements a bunch of public methods, but all these types (`H32`, ...) are private. Following change also fixes the problem:

```
➜  fixed-hash git:(master) ✗ git diff src/tests.rs
diff --git a/fixed-hash/src/tests.rs b/fixed-hash/src/tests.rs
index c587281..da14bed 100644
--- a/fixed-hash/src/tests.rs
+++ b/fixed-hash/src/tests.rs
@@ -1,8 +1,8 @@
-construct_fixed_hash! { struct H32(4); }
-construct_fixed_hash! { struct H64(8); }
-construct_fixed_hash! { struct H128(16); }
-construct_fixed_hash! { struct H160(20); }
-construct_fixed_hash! { struct H256(32); }
+construct_fixed_hash! { pub struct H32(4); }
+construct_fixed_hash! { pub struct H64(8); }
+construct_fixed_hash! { pub struct H128(16); }
+construct_fixed_hash! { pub struct H160(20); }
+construct_fixed_hash! { pub struct H256(32); }

 impl_fixed_hash_conversions!(H256, H160);

➜  fixed-hash git:(master) ✗
```

**Comment by niklasad1** [comment]
Ok cool, seems like best way to deal with this.
