### ISSUE TITLE
Support for 32 bits and big endian

### ISSUE THREAD

**Issue by mpapierski** [paritytech/parity-common#27]
Hey guys,

I was playing around with Parity tech and I was wondering how hard it would be to add support for big endian & 32 bit architectures such as MIPS/MIPS64?

**Comment by dvdplm** [comment]
Hi @mpapierski – it is definitely interesting to us to work in as many places as possible and we make a "best effort" to not rely on x86-only features. That said, there is not a consistent effort to support e.g. MIPS and we do not have the infrastructure in place to run CI on such platforms.

Can you elaborate a little on what your specific needs are and where you're running into problems?

…and of course, PRs are **always** welcome!

**Comment by mpapierski** [comment]
Hey @dvdplm. Thanks for reply!

There is no problem with CI infrastructure - you can use `cross` for effortless cross compilation testing on x86. Its a matter of few more tasks in your infrastructure. Regardless of architecture the code doesn't make any assumptions regarding byte order and if you'd try to build in on big endian machine (i.e. MIPS) it fails in many places (i.e. here on MIPS[1] and here on MIPS64[2]).

Nevermind byte order - on 32 bits little endian architectures, there is one failure in RLP encoding which I believe can be disastrous on ARM in production which I believe is officially supported (errors here [3]). This is because the code uses `usize` to encode/decode binary data which is IMO wrong and incorrect as `usize` could be 32bits or 64bits depending on the target.

I also found out that unit tests aren't run on ARM or any other platform on any Parity project (correct me if I'm wrong) than X86 which could probably help catch such errors.

[1]: https://pastebin.com/CSrpwbB4
[2]: https://pastebin.com/ukQhJfbP
[3]: https://pastebin.com/vY9ChC3V

**Comment by dvdplm** [comment]
Thank you @mpapierski for this excellent overview of issues, really appreciated. As you point out, CI support for non-x86 architectures is severely lacking. We have a work-item to improve this.

As for specific issues, if you would be so kind to open issues wherever you spot code that is obviously broken such as your example for `rlp` we can address them more easily. 
I'd say fixing issues like this in the `parity-common` crates is the right place to start as it contains many of the core-types used in many other places.

Again, thank you for caring about this and for helping us improve!

**Comment by ordian** [comment]
we test `uint` on bigendian in CI and build on wasm32-unknown-unknown
