### ISSUE TITLE
[kvdb] Make column type u32 instead of Option<u32>

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-common#272]
suggested by @dvdplm 

RocksDB added column family support at some point, but wanted to preserve backwards compatibility with the older API https://github.com/facebook/rocksdb/wiki/Column-Families#backward-compatibility, so
> All key-value pairs inserted through the old API are inserted into the Column Family "default"

We don't seem to be using both default and non-default columns at the same time, so we may want to consider changing kvdb-rocksdb impl to always use column family API and kvdb operations such as [put](https://github.com/paritytech/parity-common/blob/92ec1826884281820ebbbfc428e6c0fbdcccb9bf/kvdb/src/lib.rs#L75) and [delete](https://github.com/paritytech/parity-common/blob/92ec1826884281820ebbbfc428e6c0fbdcccb9bf/kvdb/src/lib.rs#L89) and others  would need to be changed to accept `u32` instead of `Option<u32>` as a column type. 

This would be a breaking change to `kvdb`, `kvdb-rocksdb`, `kvdb-memorydb`, `kvdb-web` and downstream crates.

**Comment by zrzka** [comment]
> We don't seem to be using both default and non-default columns at the same time.

Is this statement valid? I might miss something, but based on a quick research ...

* `parity-ethereum` - 9 columns, 4 columns in migration tests
* `substrate` - 10 columns
* `polkadot` - 2 columns

... it seems that there's no usage of default column. But I didn't check all the repositories, just few of them.

Which leads to new questions ...

* Does it make sense to keep the `impl Default for DatabaseConfig` around? Probably not, as the API requires (will) column index aka at least 1 column should be created.
* What should be done about `None => 0`, `Some(col) => col + 1`? Seems that it can be removed as well, column index can be used directly as it is, but it will probably lead to migrations (different column index).

**Comment by ordian** [comment]
> it seems that there's no usage of default column.

Default column is used at least in [the secret store](https://github.com/paritytech/parity-ethereum/blob/4c3be46f935e0ed1c716ea5cb4491e7dd499efaf/parity/db/rocksdb/mod.rs#L60-L68) in parity-ethereum.

> Does it make sense to keep the impl Default for DatabaseConfig around? Probably not, as the API requires (will) column index aka at least 1 column should be created.

Not sure what you mean here, the default impl sets other fields like `max_open_files` as well. Do you mean we should disallow setting columns to 0? We could use something like [`NonZerou32`](https://doc.rust-lang.org/std/num/struct.NonZeroU32.html) for that.
> What should be done about None => 0, Some(col) => col + 1? Seems that it can be removed as well, column index can be used directly as it is, but it will probably lead to migrations (different column index).

Yeah, we'd like to avoid migrations if possible, so I don't know if we want to remove it.

**Comment by zrzka** [comment]
> Default column is used at least in the secret store in parity-ethereum.

Thanks, wasn't searching for `Database::open_default` and missed these.

> Not sure what you mean here, the default impl sets other fields like max_open_files as well. Do you mean we should disallow setting columns to 0? We could use something like NonZerou32 for that.

Yep, something like this. But even with `NonZerou32`, there must be some default value for number of columns which should be ...? `1`?

Then the `DatabaseConfig::with_columns` should accept anything greater than 0, because the API will require a column index (`Option<u32>` -> `u32`) and it doesn't make sense to have a DB without columns when the API requires at least one.

What bothers me more is this logic ...

```rust
fn to_overlay_column(col: Option<u32>) -> usize {
    col.map_or(0, |c| (c + 1) as usize)
}
```

... if the `+ 1` will be kept ...

```rust
fn to_overlay_column(col: u32) -> usize {
    col as usize + 1
}
```

... how one would access already existing DB & column `0`? Like the `secret-store` which is using `PersistentKeyStorage` & `None`. An example:

```rust
	fn insert(&self, document: ServerKeyId, key: DocumentKeyShare) -> Result<(), Error> {
		let key: SerializableDocumentKeyShareV3 = key.into();
		let key = serde_json::to_vec(&key).map_err(|e| Error::Database(e.to_string()))?;
		let mut batch = self.db.transaction();
		batch.put(None, document.as_bytes(), &key);     <-
		self.db.write(batch).map_err(Into::into)
	}
```

It seems to me that this logic (`+ 1`) should be removed too otherwise you can't access it. But then the API breaking change wont be about `Option<u32>` -> `u32` only, but also all column indexes will be off by one. Which means that [`COLUMN_META`](https://github.com/paritytech/substrate/blob/042dc459f3875d65bec412068ba1939172c5e8c2/client/db/src/utils.rs#L41) should be changed from ...

```rust
pub const COLUMN_META: Option<u32> = Some(0);
```

... to ...

```rust
pub const COLUMN_META: u32 = 1;
```

Are you aware of this? Or am I misunderstanding it?

**Comment by ordian** [comment]
> Yep, something like this. But even with NonZerou32, there must be some default value for number of columns which should be ...? 1?

Yes, `open_default` already creates a table with 1 (default) column.

> Then the DatabaseConfig::with_columns should accept anything greater than 0, because the API will require a column index (Option<u32> -> u32) and it doesn't make sense to have a DB without columns when the API requires at least one.

Right, I was suggesting to change the type of the number of columns to `NonZerou32`, not the type of the columns, so `DatabaseConfig::with_columns` will take `NonZerou32` as a param.

> how one would access already existing DB & column 0? 

We change all the columns in the consumer crates like parity-ethereum, etc
from `Some(i)` -> `i + 1`
and from `None` -> `0`

**Comment by zrzka** [comment]
> We change all the columns in the consumer crates like parity-ethereum

Okay, so the answer to my question if you're aware of this is -> yes :) Good. I've got a PR for this, but not finished yet. Will finish it tomorrow.

**Comment by dvdplm** [comment]
> We change all the columns in the consumer crates like parity-ethereum, etc
> from `Some(i)` -> `i + 1`
> and from `None` -> `0`

So this is not quite right. It would have been correct for overlay "columns", but for the rocksdb column families it's: `Some(0)` is translated into `col0`, `Some(N)` into `colN` etc. This means that consumer crates that use the default column, aka `None` will need a migration. :/
