### ISSUE TITLE
[primitive-types] Implement metadata traits for the primitive_types::U256

### ISSUE THREAD

**Issue by Poggi-Luca** [paritytech/parity-common#311]
I'm coding a smart contract with Parity Ink! in which I have to store an unsigned 256-bit number (u256 not supported by Rust), so I planned to import `primitive-types` by adding:
- `primitive-types = { version = "0.6.2", default-features = false, features = ["codec"] }` in `Cargo.toml` file;
- `use primitive_types::U256;` in `lib.rs` file.
By running `cargo contract build` --> NO ERRORS and `wasm` file generated correctly.
But when running `cargo contract generate-metadata`, I get the following errors:
```
error[E0277]: the trait bound `primitive_types::U256: type_metadata::type_id::HasTypeId` is not satisfied
   --> lib.rs:8:1
    |
8   | #[ink::contract(version = "0.1.0")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `type_metadata::type_id::HasTypeId` is not implemented for `primitive_types::U256`
    | 
   ::: /home/luca/.cargo/git/checkouts/ink-1add513eda8f5a89/8bcf381/abi/src/specs.rs:625:12
    |
625 |         T: Metadata,
    |            -------- required by this bound in `ink_abi::specs::TypeSpec::with_name_segs`
    |
    = note: required because of the requirements on the impl of `type_metadata::Metadata` for `primitive_types::U256`

error[E0277]: the trait bound `primitive_types::U256: type_metadata::type_def::HasTypeDef` is not satisfied
   --> lib.rs:8:1
    |
8   | #[ink::contract(version = "0.1.0")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `type_metadata::type_def::HasTypeDef` is not implemented for `primitive_types::U256`
    | 
   ::: /home/luca/.cargo/git/checkouts/ink-1add513eda8f5a89/8bcf381/abi/src/specs.rs:625:12
    |
625 |         T: Metadata,
    |            -------- required by this bound in `ink_abi::specs::TypeSpec::with_name_segs`
    |
    = note: required because of the requirements on the impl of `type_metadata::Metadata` for `primitive_types::U256`

```
It seems a problem related to lack of implementations of some metadata traits for the `primitive_types::U256` type.
Could someone implement those traits in the `type-metadata` crate or wrap the `primitive_types::U256` type in a tuple-struct and implement the trait on it.

Thank you

**Comment by thiolliere** [comment]
If we want primitive-types to be able to be used easily from ink maybe we could implement the trait behind a feature similarly to codec.

Or alternatively ink contract developer should create a wrapping struct or new struct for it and implement metadata themself.

**Comment by dvdplm** [comment]
This sounds like something that must be dealt with in the consuming crate (`type-metadata` in this case I guess?) or further up the stack (using a wrapper type in your code such that the type is “yours”). 
If `primitive-types` were to implement this it would need to depend on the crate that defines the trait, which is not desired because we would end up with a circular dependency.

**Comment by ordian** [comment]
@Poggi-Luca if you want an example of how this wrapper might look like, add
```toml 
type-metadata = { version = "0.1", features = ["derive"] }
```
 to your `Cargo.toml` `[dependencies]` section.
and use `U256Wrapper` instead of `U256` in your `lib.rs` 
```rust
#[derive(Metadata)]
struct U256Wrapper(pub U256);
```

> If primitive-types were to implement this it would need to depend on the crate that defines the trait, which is not desired because we would end up with a circular dependency.

`type-metadata` doesn't depend on `primitive-types`, so I'm not sure about circular dependency argument. `primitive-types` already optionally depends on `parity-scale-codec` and if `type-metadata` feature would be used in similar conditions, I see no reason why we don't want to add it to `primitive-types`. Perhaps we could expose it via high-level feature `substrate = ['impl-codec', 'type-metadata']`.

**Comment by dvdplm** [comment]
> `type-metadata` doesn't depend on `primitive-types`, so I'm not sure about circular dependency argument.

I actually have no what the `type-metadata` crate is or does, so I am probably wrong then. (But if the job of `type-metadata` is to provide metadata about types, then perhaps it should depend on `primitive-types`?)

> I see no reason why we don't want to add it to `primitive-types`

Feature creep? Or put differently: what is the criteria for adding new features here?

**Comment by bkchr** [comment]
Serde also does not depends on `primitive-types` to implement the serde traits, it is the other way around ;) And I think we should stick to this. Ink! requires this and in the future Substrate as well. It is not perfect, but Rust does not offers us any better way of doing it.

**Comment by dvdplm** [comment]
Okkie dokkie, let's do it then.

**Comment by tomusdrw** [comment]
We already have `construct_uint!` macros I believe that make it super easy to just create a separate `U256` structure. Is there any need to interop between ink contracts and any other crates that depend on `primitive-types` or between two different ink contracts? I'm not 100% sure that it's the right way to implement it here as a feature, but happy to be convinced otherwise.

**Comment by ascjones** [comment]
> What's the use case?

I believe it will be to use `type-metadata` to provide richer metadata. See e.g. https://github.com/paritytech/substrate/issues/917

**Comment by tomusdrw** [comment]
Fair enough, sounds good then.

**Comment by dvdplm** [comment]
I am still a bit skeptical about going down this route. Where do we stop adding features with meta data impls? Need it for `fixed-hash` as well (paritytech/substrate#917 mentions `Address`)? And crypto types (`Public`/`Secret`)? It's not obvious to me that this is concern for `primitive-types`. 

The argument that we do this for serde and codec already is a decent one so I won't make a fuss.

**Comment by Poggi-Luca** [comment]
> @Poggi-Luca if you want an example of how this wrapper might look like, add
> 
> ```toml
> type-metadata = { version = "0.1", features = ["derive"] }
> ```
> 
> to your `Cargo.toml` `[dependencies]` section.
> and use `U256Wrapper` instead of `U256` in your `lib.rs`
> 
> ```rust
> #[derive(Metadata)]
> struct U256Wrapper(pub U256);
> ```

Thank you! I didn’t know how a wrapper might looks like! 😁

**Comment by Poggi-Luca** [comment]
@ordian I'm coding smartcontracts on ChainX and the problem is that ChainX is based on an old version of substrate. So I have to use some `dependencies` feature with `old-codec` to make the code running correctly. In this way, I have also to use an old version of `primitive types` that use `parity-codec-3.0` (not `parity-scale-codec`). So, using Github compare function, I finded `primitive-types 0.3.0 version`. Dependencies section of `Cargo.toml` file is:
```
[dependencies]
ink_abi = { git = "https://github.com/chainx-org/ink", branch = "ink2.0", package = "ink_abi", default-features = false, features = ["derive"], optional = true }
ink_core = { git = "https://github.com/chainx-org/ink", branch = "ink2.0", package = "ink_core", default-features = false, features = ["old-codec"] }
ink_lang2 = { git = "https://github.com/chainx-org/ink", branch = "ink2.0", package = "ink_lang2", default-features = false, features = ["old-codec"] }

scale = { package = "parity-codec", version = "3.5", default-features = false, features = ["derive"] }
type-metadata = { git = "https://github.com/type-metadata/type-metadata.git", default-features = false, features = ["derive"], optional = true }
primitive-types = { version = "0.3.0", default-features = false, features = ["codec"] }
```
By running `cargo-contract contract build` --> NO ERRORS and `wasm` file generated correctly.
By running `cargo-contract contract generate-metadata`, I get the same error about metadata.
So, which option you suggest me:
1) Fork primitive-types version 0.3.0 (codec version OK) and add the modifications you propose in pull request #312 
2) Fork primitive-types version 0.6.2 (latest version), then add modifications to codec version and modifications you propose in pull request #312 

What is the possible and simplest way? Thank you

**Comment by ordian** [comment]
@Poggi-Luca sorry for the late reply, I think the easiest option is 1, if the chainX still uses primitive-types v0.3, upgrading to 0.6 could be quite evolved.

**Comment by Poggi-Luca** [comment]
@ordian I made the changes you propose in #312 but I get the same error: https://github.com/Poggi-Luca/parity-common-primitive-types-v0.3.0

Now the Dependencies section of `Cargo.toml` file is:
```
[dependencies]
ink_abi = { git = "https://github.com/chainx-org/ink", branch = "ink2.0", package = "ink_abi", default-features = false, features = ["derive"], optional = true }
ink_core = { git = "https://github.com/chainx-org/ink", branch = "ink2.0", package = "ink_core", default-features = false, features = ["old-codec"] }
ink_lang2 = { git = "https://github.com/chainx-org/ink", branch = "ink2.0", package = "ink_lang2", default-features = false, features = ["old-codec"] }

scale = { package = "parity-codec", version = "3.5", default-features = false, features = ["derive"] }
type-metadata = { git = "https://github.com/type-metadata/type-metadata.git", default-features = false, features = ["derive"], optional = true }
primitive-types = { git = "https://github.com/Poggi-Luca/parity-common-primitive-types-v0.3.0", default-features = false, features = ["codec"] } 
```
By running `cargo-contract contract build` --> NO ERRORS and wasm file generated correctly.
By running `cargo-contract contract generate-metadata`, I get the following error:
```
error[E0277]: the trait bound `primitive_types::U256: type_metadata::type_id::HasTypeId` is not satisfied
   --> lib.rs:8:1
    |
8   | #[ink::contract(version = "0.1.0")]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `type_metadata::type_id::HasTypeId` is not implemented for `primitive_types::U256`
    | 
   ::: /home/luca/.cargo/git/checkouts/ink-9c358e34fc403586/024347d/abi/src/specs.rs:625:12
    |
625 |         T: Metadata,
    |            -------- required by this bound in `ink_abi::specs::TypeSpec::with_name_segs`
    |
    = note: required because of the requirements on the impl of `type_metadata::Metadata` for `primitive_types::U256`

```

**Comment by ordian** [comment]
> primitive-types = { git = "https://github.com/Poggi-Luca/parity-common-primitive-types-v0.3.0", default-features = false, features = ["codec"] } 

I see you haven't enabled `type-metadata` feature,
```
primitive-types = { git = "https://github.com/Poggi-Luca/parity-common-primitive-types-v0.3.0", default-features = false, features = ["codec", "type-metadata"] } 
```
Also make sure you're using the version of `type-metadata` as `chain-x/ink`. Feel free to ping me on riot for further discussion (I've created a direct chat).
