### ISSUE TITLE
Consider relicensing `parity-crypto`

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-common#321]
It would be cool to relicense `parity-crypto` to a more permissive license (`Apache2`) as it contains a lot of battle-tested cryptoprimitives that are quite useful for external projects.

AFAIU, the actions required are:
1. Make sure that all contributions were done under CLA
2. Make sure that all deps are non-GPL (:heavy_check_mark: as of 2020-01-29; head hash: de318bf)
3. Get Parity Technologies (IP/Copyright owner) consent (tentative :white_check_mark: from Gav)

Anything else I'm missing?

**Comment by ordian** [comment]
> Make sure that all contributions were done under CLA

cc @TovarishFin

**Comment by TovarishFin** [comment]
I have a set of scripts that I have already written for other purposes that can be used to get the relevant data for this repo as well. I ran the scripts and am pretty sure that I have all of the needed data ready. 

It of course still does need review by someone who has a decent understanding of licenses (this is not me!) I just need to know who to send this information to.

**Comment by ordian** [comment]
Closed by #342
