### ISSUE TITLE
Implementing post-quantum crypto in parity_crypto

### ISSUE THREAD

**Issue by jon-chuang** [paritytech/parity-common#322]
From what I understand, parity_crypto is a pure Rust module utilising pure Rust implementations sourced from multiple small crates of some limited set of cryptographic primitives.

Some questions - why not use some other implementations like [RustCrypto](https://github.com/RustCrypto/) or [ring](https://github.com/briansmith/ring/) (not pure rust)? 

I wonder if it would be worth implementing and testing some hybrid post-quantum crypto primitives, since [AWS](https://aws.amazon.com/blogs/security/post-quantum-tls-now-supported-in-aws-kms/) has started to do so. On the other hand, some good reference implementations for a larger subset of the NIST round 2 algorithms (e.g. https://github.com/open-quantum-safe) already exist.

**Comment by dvdplm** [comment]
> From what I understand, parity_crypto is a pure Rust module utilising pure 

Not really: we're using `rust-secp256k1` which is wrapper around the homonymous C-library, but sure, there's a preference for more Rust code for sure.

We use parts of RustCrypto, e.g. `digest`, `sha2` and others.

> I wonder if it would be worth implementing and testing some hybrid post-quantum crypto primitives

`parity-crypto` is, at least today, pretty specifically written for the needs of Parity projects and aims to be a production level code base. It is not the proper place for experiments, and for the moment, quantum crypto is not in use in any of our projects.
