### ISSUE TITLE
MallocSizeOf panics on Android

### ISSUE THREAD

**Issue by tomaka** [paritytech/parity-common#354]
We reach this line when trying to run Substrate on Android:
https://github.com/paritytech/parity-common/blob/46d8f6b5419edea4c7b2d46a09ecf3bee3facc7b/parity-util-mem/src/allocators.rs#L109

**Comment by ordian** [comment]
does substrate use `jemalloc-global` feature of `parity-util-mem`?

**Comment by tomaka** [comment]
Substrate doesn't use jemalloc (and we don't want to force that on users), so I don't think that's appropriate.

**Comment by ordian** [comment]
cc @cheme

https://github.com/paritytech/parity-common/blob/46d8f6b5419edea4c7b2d46a09ecf3bee3facc7b/parity-util-mem/src/allocators.rs#L99

maybe we should extend that to `android` as well

**Comment by ordian** [comment]
@tomaka could you test #355?

**Comment by cheme** [comment]
@ordian ,  #355 seems sensible, but I cannot really test, last resort should be to use jemalloc or very last resort estimate_size.
