### ISSUE TITLE
[parity-crypto] consider moving to openethereum

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-common#366]
It doesn't seem to used in substrate and only in a few crates.io crates https://crates.io/crates/parity-crypto/reverse_dependencies.

**Comment by niklasad1** [comment]
AFAIK [secret store](https://github.com/paritytech/secret-store) is using parity-crypto for both ethereum and substrate.

//cc @svyatonik @grbIzl can you confirm?

**Comment by svyatonik** [comment]
Yes - `parity-crypto` is used by Secret Store itself (I mean for running key servers, which are blockchain agnostic) extensively. SS could be used (have adapters) both with Substrate-based and Ethereum-like blockchains. It isn't on crates.io (yet?) :/

**Comment by ordian** [comment]
yeah, good point about secret-store, let's close the issue then
