### ISSUE TITLE
[kvdb] Lifetime of `iter_from_prefix`

### ISSUE THREAD

**Issue by yihuang** [paritytech/parity-common#367]
```rust
	fn iter_from_prefix<'a>(
		&'a self,
		col: u32,
		prefix: &'a [u8],
	) -> Box<dyn Iterator<Item = (Box<[u8]>, Box<[u8]>)> + 'a>;
```
The `prefix` use the same lifetime marker as `self` and return value, so the returned iterator can't live longer than prefix. I think this's not good, because prefix could be temporarily constructed. For example:

```rust
fn iter_prefix(&self, key: Key) -> impl Iterator<Item=...> {
    self.db.iter_from_prefix(SOME_COL, &key.encode())
}
```

**Comment by ordian** [comment]
This is intended. The implementations (like rocksdb) need to hold a reference to the prefix. The user is expected to store the prefix somewhere that outlives the iterator. You can create an API that returns something like
```rust
struct Iter<'a> {
    encoded_prefix: Vec<u8>,
    db: &Db,
}
impl<'a> Iter<'a> {
    fn iter(&self) -> impl Iterator<Item=...> {
        self.db.iter_from_prefix(SOME_COL, &self.encoded_prefix)
    }
}
```
We could clone the prefix somewhere in the internals of prefix iterator, but it's a question of convenience vs explicitness.

**Comment by ordian** [comment]
> The implementations (like rocksdb) need to hold a reference to the prefix.

I might be wrong on this one, let me double check.

**Comment by ordian** [comment]
It seems RocksDB impl doesn't require that, it uses `seek(prefix)` only on iterator construction [[1]](https://github.com/rust-rocksdb/rust-rocksdb/blob/0e84c3246844d94efcbab0f94915654c3828072a/src/db_iterator.rs#L405), but our `InMemory` implementation of `kvdb` currently does. I'll close the issue since there is a workaround.
