### ISSUE TITLE
building parity-util-mem fails in windows

### ISSUE THREAD

**Issue by MyronFanQiu** [paritytech/parity-common#374]
error[E0308]: mismatched types
  --> parity-util-mem\src\allocators.rs:80:23
   |
80 |                 HeapSize(heap, 0, ptr) as usize
   |                                   ^^^ expected enum `winapi::ctypes::c_void`, found enum `std::ffi::c_void`
   |
   = note: expected raw pointer `*const winapi::ctypes::c_void`
              found raw pointer `*const std::ffi::c_void`

**Comment by ordian** [comment]
I think for windows a user is supposed to use `estimate-heapsize` https://github.com/paritytech/parity-common/blob/0bba5668615e88aec23d2d2e22f7b5bae6e0932b/appveyor.yml#L29

Is that correct @cheme?

**Comment by cheme** [comment]
'estimate-heapsize' could be a way to build (mimalloc too), but the windows default call is the one from this error call.
The code is clearly from heapsize where winapi 3.4 was in use, here with 3.8 it is indeed broken.
Probably a dependency update problem, I think the easiest at this point would be to revert to 3.4 (it is probably just a small fix to use the right type, but I fear the line before may not still be needed, so it would require some windows testing).

**Comment by MyronFanQiu** [comment]
I tried to test `substrate/staking` module and met this issue. After some digging, I filed this issue. `cargo test --features=estimate-heapsize` works for `parity-util-mem`. Is there any workaround to test `substrate/staking` as well?

**Comment by cheme** [comment]
My best bet for quick 'do not merge' workaround would be to add 'estimate-heapsize' feature next to 'std' feature of substrate, eg 
```
--- a/client/db/Cargo.toml
+++ b/client/db/Cargo.toml
@@ -16,7 +16,7 @@ kvdb-rocksdb = { version = "0.7", optional = true }
 kvdb-memorydb = "0.5.0"
 linked-hash-map = "0.5.2"
 hash-db = "0.15.2"
-parity-util-mem = { version = "0.6.0", default-features = false, features = ["std"] }
+parity-util-mem = { version = "0.6.0", default-features = false, features = ["std", "estimate-heapsize"] }
 codec = { package = "parity-scale-codec", version = "1.3.0", features = ["derive"] }
```
and maybe also
```
--- a/primitives/runtime/Cargo.toml
+++ b/primitives/runtime/Cargo.toml
@@ -46,6 +46,7 @@ std = [
        "serde",
        "sp-inherents/std",
        "parity-util-mem/std",
+       "parity-util-mem/estimate-heapsize",
        "hash256-std-hasher/std",
 ]
```

**Comment by ordian** [comment]
Although when I try to import it I get this weird error
```
  |
3 | use winapi::ctypes::c_void as winapi_c_void;
  |             ^^^^^^ could not find `ctypes` in `winapi`
```
any hints?

**Comment by cheme** [comment]
Indeed, I am really not sure anymore about 0.3.4, I did check for reference heasize crate and I am starting to think it never work (if it was working there should have been the feature 'heaphead' in the import), so reverting is probably a dumb idea, upgrading seems the way to go, I am not very confident with `ptr = *(ptr as *const *const c_void).offset(-1);` though but with a windows VM it could be checked.

**Comment by ordian** [comment]
FWIW tests in #375 seem to pass

**Comment by MyronFanQiu** [comment]
Thanks for such a quick action.
