### ISSUE TITLE
Help with primitive-types

### ISSUE THREAD

**Issue by Kevan0v** [paritytech/parity-common#401]
I am struggling with primitive-types:

```
cannot use `|=` on type `primitive_types::U256`
```

Is there a work around for using these combined operators? Also is there a simple way to flip a bit at a given position? Thanks!

**Comment by ordian** [comment]
`uint` doesn't implement `BitOrAssign`, but implements `BitOr` trait, meaning you can do
```rust
a = a | b
```
`BitOrAssign` (as well as `BitAndAssign` and `BitXorAssign`) would be easy to implement, PRs are welcome! :)
