### ISSUE TITLE
Add missing ethereum-types version tags

### ISSUE THREAD

**Issue by artob** [paritytech/parity-common#439]
The version tags for [ethereum-types](https://crates.io/crates/ethereum-types) in this GitHub repository appear to begin with the [0.5.3-beta.1](https://github.com/paritytech/parity-common/releases/tag/ethereum-types-v0.5.3-beta.1) release.

This is problematic as there are still new downstream project releases pulling in older versions (see, in particular, https://github.com/openethereum/openethereum/issues/88) and it'd be truly helpful to know which commits such versions correspond to, as well as to use GitHub to browse the old code and to produce diffs to newer releases.

Would it be possible to push the older tags as well? At least [0.4.2](https://crates.io/crates/ethereum-types/0.4.2), pretty please. (Possibly related: https://github.com/paritytech/parity-common/pull/68)

**Comment by ordian** [comment]
Hi,
judging by this commit https://github.com/paritytech/parity-common/commit/0b53e91ef161915d3c37568c04f42bb519664e0c
and https://github.com/paritytech/parity-common/pull/97, version 0.4.2 was not published from the master branch of this repo, so I can't push the tags, sorry.

However, you can find the sources here https://docs.rs/crate/ethereum-types/0.4.2/source/src/.

**Comment by artob** [comment]
Thanks, @ordian. From comparing the hashes of the source files in the 0.4.2 crate to the relevant timeline of commits in this repository, it does look like there is no commit in this repository that would correspond to that version. The 0.4.2 version must've been released sometime between commits between 4e8182f683d34c525192d7e42005f6a4ac008381 and 97deed79198445708050ae13dd93fb3a5672d4e0. All right, it is as it is.
