### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by gguoss** [paritytech/parity-common#45]
github.com-1ecc6299db9ec823/triehash-0.1.2/src/lib.rs:141:2
138 | fn gen_trie_root<A: AsRef<[u8]>, B: AsRef<[u8]>>(input: &[(A, B)]) -> H256 {
    |                                                                       ---- expected `ethereum_types::H256` because of return type
...
141 |     keccak(stream.out())
    |     ^^^^^^^^^^^^^^^^^^^^ expected struct `ethereum_types::H256`, found struct `hash::H256`
    |
    = note: expected type `ethereum_types::H256`
               found type `hash::H256`

**Comment by dvdplm** [comment]
Hi, not sure what the context is here, but can you try with triehash` v0.2.1?

**Comment by gguoss** [comment]
step by step:
- git clone https://github.com/paritytech/substrate
- cargo update
- cargo build
then build error
