### ISSUE TITLE
full_shl initializes buffer with 64 instead of 0

### ISSUE THREAD

**Issue by defigure** [paritytech/parity-common#454]
Surely 064 is a typo of 0u64

https://github.com/paritytech/parity-common/blob/adc85bf161a14f171bf1713bf66a09d311212f9c/uint/src/uint.rs#L684

**Comment by niklasad1** [comment]
Yeah, nice catch.

**Comment by ordian** [comment]
right, but it doesn't really matter because `u` is completely overwritten

**Comment by dvdplm** [comment]
@defigure thanks for signalling this, do you want to make a PR or want us to take care of it?

**Comment by defigure** [comment]
> @defigure thanks for signalling this, do you want to make a PR or want us to take care of it?

Go for it, thanks
