### ISSUE TITLE
[parity-crypto]: a test fails when running locally

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-common#472]
A test `secrets_are_zeroed_on_drop` https://github.com/paritytech/parity-common/blob/46d8f6b5419edea4c7b2d46a09ecf3bee3facc7b/parity-crypto/src/hmac/test.rs#L236-L252

fails on Linux when running locally with `cd parity-crypto; cargo test --all-features`:
```
failures:

---- hmac::test::secrets_are_zeroed_on_drop stdout ----
thread 'hmac::test::secrets_are_zeroed_on_drop' panicked at 'assertion failed: `(left == right)`
  left: `Sha256([0, 64, 242, 249, 7, 0])`,
 right: `Sha256([0, 0, 0, 0, 0, 0])`', parity-crypto/src/hmac/test.rs:250:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```
 but succeeds on CI.
Investigate why.

Reported by @niklasad1.

**Comment by niklasad1** [comment]
I think the test is wrong, looks like UB to me
https://github.com/paritytech/parity-common/blob/master/parity-crypto/src/hmac/test.rs#L250, ptr is a dangling pointer there.
It points to signing_key which is dropped in the block above.

**Comment by ordian** [comment]
True, is there a safe way to inspect memory after the value is dropped?

**Comment by ordian** [comment]
If no, we should just remove the test.

**Comment by niklasad1** [comment]
I don't know to be honest,  the OS could do whatever it wants the memory but I think the problem is that pointer doesn't `point` at start the actual buffer that gets `zeroed`.

I find it very unlikely that OS writes other stuff at the memory location where the buffer was allocated before during the tests though....
