### ISSUE TITLE
ethereum-types/std always pulls in codec

### ISSUE THREAD

**Issue by vorot93** [paritytech/parity-common#475]
The correct logic should be "pull codec/std _if codec is enabled_".

**Comment by ordian** [comment]
this is fixed only in cargo nightly: https://github.com/rust-lang/cargo/issues/8832

**Comment by ordian** [comment]
specifically, this line https://github.com/paritytech/parity-common/blob/54076a524e5d28405b3a4ad3146a108c928998a2/primitive-types/Cargo.toml#L20 pulls in codec, this could be fixed by enabling nightly feature mentioned above
