### ISSUE TITLE
RLP decoding of non-canonical length encodings

### ISSUE THREAD

**Issue by mguillemot-tel** [paritytech/parity-common#49]
According to the [RLP spec](https://github.com/ethereum/wiki/wiki/RLP#implementations), RLP elements (string or list) of encoded length > 55 should be encoded with a long encoding, and RLP elements with an encoded length <= 55 should be encoded with a short encoding.

It is currently possible to decode **RLP elements of length <= 55 encoded with the long encoding** without raising any error.

I am not sure there is harm in this, but this means we can have 2 different binary RLPs that have exactly the same semantics, which seems a bit fishy in some situations.

Some failing examples:

```rust
#[test]
fn test_canonical_string_encoding() {
	assert_ne!(Rlp::new(&vec![0xc0 + 4, 0xb7 + 1, 2, b'a', b'b']).val_at::<String>(0),
			   Rlp::new(&vec![0xc0 + 3, 0x82, b'a', b'b']).val_at::<String>(0)); // fails

}

#[test]
fn test_canonical_list_encoding() {
	assert_ne!(Rlp::new(&vec![0xc0 + 3, 0x82, b'a', b'b']).val_at::<String>(0),
			   Rlp::new(&vec![0xf7 + 1, 3, 0x82, b'a', b'b']).val_at::<String>(0)); // fails

}
```

**Comment by dvdplm** [comment]
cc @debris
