### ISSUE TITLE
[BUG] Build error caused by broken changes in a dependency

### ISSUE THREAD

**Issue by PumpkinSeed** [paritytech/parity-common#525]
The `ethereum-types` crate is failed to build because of the certain changes in bitvec. 
Related issue: https://github.com/bitvecto-rs/bitvec/issues/105

So, `bitvec` used by `parity-scale-codec`,
`parity-scale-codec` used by `impl-codec`,
`impl-codec` used by `primitive-types`,
`primitive-types` used by `ethereum-types`.

**Comment by dvdplm** [comment]
See https://github.com/paritytech/parity-scale-codec/pull/250

**Comment by ordian** [comment]
Let's repurpose this issue as note, that we should remove this CI workaround: #527 when https://github.com/bitvecto-rs/bitvec/issues/105 is resolved.
