### ISSUE TITLE
Publish updated `kvdb-rocksdb` to Crates.io (apple silicon M1 ARM chips)

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/parity-common#541]
The published https://crates.io/crates/kvdb-rocksdb/ is lagging behind master. 

A fix is now in place to enable apple silicon M1 ARM chips build issues with the `rocksdb` 0.16.0 release, that is now in the master, but not on crates.io

Although may not be strictly necessary, as the cargo respolver](https://doc.rust-lang.org/cargo/reference/resolver.html) _should_ discover this version and use it instead of 0.15.0.

solves https://github.com/paritytech/substrate/issues/8507

**Comment by NukeManDan** [comment]
on substrate, I can't get `cargo update -p rocksdb --precise 0.16.0` to resolve:
```
    Updating crates.io index
error: failed to select a version for the requirement `rocksdb = "^0.15"`
candidate versions found which didn't match: 0.16.0
location searched: crates.io index
required by package `kvdb-rocksdb v0.11.0`
    ... which is depended on by `sc-client-db v0.9.0 (/home/dan/git/substrate/client/db)`
    ... which is depended on by `sc-service v0.9.0 (/home/dan/git/substrate/client/service)`
    ... which is depended on by `node-template v3.0.0 (/home/dan/git/substrate/bin/node-template/node)`
```
so a release (with a new patch? 0.11.1 ?)  and possibly a few more updates will be required, it seems

**Comment by ordian** [comment]
@NukeManDan the M1 issue is already solved in substrate and polkadot by upgrading `librocksdb-sys`, see https://github.com/paritytech/polkadot/pull/2899. We don't have to bump `rocksdb` for that.
