### ISSUE TITLE
implement num_traits::int::PrimInt for U256 / U512

### ISSUE THREAD

**Issue by xlc** [paritytech/parity-common#551]
This allow U256 / U512 to be used with crates like `integer-sqrt`

**Comment by ordian** [comment]
Such an implementation would have to go into https://github.com/paritytech/parity-common/blob/master/primitive-types/impls/num-traits/src/lib.rs.

But it might be worth implementing integer_sqrt directly in `uint` as well.

**Comment by ordian** [comment]
Published `uint` 0.9.1 and `impl-num-traits` 0.1.1
