### ISSUE TITLE
Triage unused/abandoned(?) crates

### ISSUE THREAD

**Issue by Xanewok** [paritytech/parity-common#560]
While working on #552 I noticed that we have quite a bit of crates that are not (will not be?) used, e.g.
- [transaction-pool](https://github.com/paritytech/parity-common/tree/master/transaction-pool) ([crates.io dependents](https://crates.io/crates/transaction-pool/reverse_dependencies) - 2 vapory crates with < 100 downloads)
doesn't seem to be used here nor in Substrate - is it superseded by sc-transaction-pool?
- [contract-address](https://github.com/paritytech/parity-common/tree/master/contract-address) ([crates.io dependents](https://crates.io/crates/contract-address/reverse_dependencies) - none)
newtype around `ethereum_types::Address` and 3 functions which basically do simple buffer concatenation - does it warrant a separate crate or maybe this can be upstreamed into `ethereum_types`?
- [trace-time](https://github.com/paritytech/parity-common/tree/master/trace-time) ([crates.io dependents](https://crates.io/crates/trace-time/reverse_dependencies) - transaction-pool ^0.1 and 4 vapory deps with <100 downloads)
this is a simple drop guard type that calls specifically `log::trace!` with a `&'static str` label and calculates elapsed time using `Instant::elapsed` - not flexible enough to be used in production and for simple debugging it's better to just roll your own simple macro/type inline, so that it ties to the existing logging/perf infra.

I don't think we plan to continue using or updating them and if we bump some crates here that these depend on, this introduces busywork like updating relevant changelog or bumping and releasing new versions of these crates (which will probably continue to be unused).

Should we decommission them?

**Comment by ordian** [comment]
Yes, please! `transaction-pool` was there to be shared between parity-ethereum (aka openethereum, which is unmaintained) and substrate. `contract-address` to be used by https://github.com/comit-network/comit-rs, which is archived. `trace-time`, IDK, safe to remove anyway.

I'd like to add to this list (some parts of) parity-crypto, kvdb-web (only used in browser demo, but can be replaced with kvdb-memorydb).

**Comment by dvdplm** [comment]
> Should we decommission them?

Yes please.

**Comment by dvdplm** [comment]
I wonder if anyone uses `triehash` and `plain_hasher`. I'd be keen to get rid of those too.

**Comment by ordian** [comment]
@dvdplm they might be used by https://github.com/paritytech/parity-bridges-common and https://github.com/paritytech/frontier

cc @tomusdrw, @sorpaas

**Comment by tomusdrw** [comment]
We do use both in bridges, but it's only for PoA bridge, which is also soft-deprecated. If there are any changes necessary we can always look into the history and split these out to our (or separate) repositories.

I'm fine with removing all crates mentioned in this issue.
