### ISSUE TITLE
[uint] `Display` formatting

### ISSUE THREAD

**Issue by uint** [paritytech/parity-common#584]
Hi! Currently the [`std::fmt::Display` implementation in `uint`](https://github.com/paritytech/parity-common/blob/master/uint/src/uint.rs#L54-L61) is incomplete.

It ignores formatting options that may be passed to it through the `Formatter`, so if we try to e.g. add some padding, things don't work as expected.

**Comment by ordian** [comment]
Hey, do you mean this code? https://github.com/paritytech/parity-common/blob/c031b0971c3683ac9f2ab6b365064979afa24588/uint/src/uint.rs#L1651-L1706

PRs are welcome :) Alternatively, if you could describe the syntax and expected behavior we could implement that quickly.

**Comment by uint** [comment]
Yes, my bad, pointed to the wrong thing hastily.

I'm mostly interested in these types applying padding properly when being formatted with something like `{:018}`. It **might** (?) be as simple as changing this line:
```diff
- f.write_str(s) 
+ f.pad_integral(true, "", s)
```

I might take a shot at it at some point this week.
