### ISSUE TITLE
[parity-util-mem] Consider using `tikv-jemallocator` instead of `jemallocator`

### ISSUE THREAD

**Issue by ordian** [paritytech/parity-common#586]
https://github.com/rust-lang/rust/pull/83152
https://docs.rs/tikv-jemallocator
https://github.com/rust-rocksdb/rust-rocksdb/pull/554

**Comment by koute** [comment]
Good idea; I'll try to run some basic performance/memory tests and push a PR.

**Comment by koute** [comment]
From very rough tests it looks like the CPU usage is mostly unchanged, but the peak RSS memory usage is around ~10% lower, so should be worth migrating to!
