### ISSUE TITLE
RocksDB LOG file rotation.

### ISSUE THREAD

**Issue by ruseinov** [paritytech/parity-common#606]
We're facing an issue with substrate that has to do with RocksDB writing to a single LOG file, that's never rotated and has no size limit. It would be nice to have a solution for limiting the log size/truncating/rotating and eventually deleting the log files. That currently does not seem configurable through `kvdb-rocksdb`. 

While it's still possible to rotate the logs externally, this gets much harder when it has to be done on a node that is owned by an external user/validator.

**Comment by ordian** [comment]
We already expose `keep_log_file_num` in the config, we could expose other methods: https://github.com/rust-rocksdb/rust-rocksdb/pull/433.

**Comment by ordian** [comment]
> We already expose `keep_log_file_num` in the config,

it seems it's not used correctly

**Comment by ordian** [comment]
We can expose
1. https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_db_log_dir
2. https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_recycle_log_file_num
3. https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_max_log_file_size

would that work for you?

**Comment by ruseinov** [comment]
> We can expose
> 
> 1. https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_db_log_dir
> 2. https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_recycle_log_file_num
> 3. https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_max_log_file_size
> 
> would that work for you?

Yes, that's perfect!

**Comment by ruseinov** [comment]
@ordian But in order for this to work in substrate there's also some plumbing to be done in a bunch of crates, right?
Like sc-service and sc-client-db.

**Comment by ordian** [comment]
Sorry, I didn't post my comment for some reason.

Yeah, there is some plumbing that needs to be done to expose these. We can do the following:
1. Provide some sane defaults
2. Allow configuring the options via env variables as well (with a priority to env variable).
3. Expose some of the config options here: https://github.com/paritytech/substrate/blob/fd350e3c02d7fb9421d908e6c552d50992b167ea/client/db/src/lib.rs#L332-L337.

@bkchr what are your what's on this?

**Comment by bkchr** [comment]
Why not switch to paritydb?

Rocksdb is on its way of being removed in Substrate.

**Comment by ruseinov** [comment]
> Why not switch to paritydb?
> 
> Rocksdb is on its way of being removed in Substrate.

I guess it would still be nice to support these for backwards compatibility with the old nodes/substrate versions and just for having something that works well out of the box.

**Comment by bkchr** [comment]
Substrate 3.0.0 is not supported by us. Aka we don't backport anything. I mean, if you want to fork and do it yourself, you can do it.

**Comment by ruseinov** [comment]
Got it, thanks!

**Comment by ruseinov** [comment]
Basically the problem is that substrate 4.0.0 is not a stable release yet and storage in 3.0.0 is a pain to work with. But we’ll work around that for now.

**Comment by ruseinov** [comment]
> I would not bet on any Substrate 4.0.0 release in the near future. You could try one of the monthly releases for example to have something newer.

Got it. Well, we’re trying to maintain a sort of stability to the network that is currently being run. I am not sure if monthly releases are a way to go for that, but at the same time the 3.0.0 version has it’s downsides. Thanks for the insight!

**Comment by ruseinov** [comment]
@bkchr Just one last question since we are already having this conversation:
What's the vision for the upcoming Substrate versions: any chance 4.0.0 would be the one with long term support?

I guess we will start migrating our stuff to monthly bleeding-edge releases as there is no point in maintaining 3.0.0-based version with the deprecated storage and other issues.

**Comment by bkchr** [comment]
> What's the vision for the upcoming Substrate versions: any chance 4.0.0 would be the one with long term support?

We will probably shift more to a rolling release model. However, keeping interfaces more stable.

**Comment by ordian** [comment]
closing as wontfix since we're deprecating kvdb-rocksdb

**Comment by ruseinov** [comment]
@bkchr I have got one question in regards to this ticket - we're currently running on 3.0.0 and looking to upgrade, at least the storage. As rocksDB is a pain to maintain having to cleanup the logs, it also takes lots of space for 2kk+ blocks. Not sure if parityDB is any better in that regard.
But since the substrate repo is still on 4.0.0-dev and polkadot 0.9.18 is using a custom branch - I can't help but wonder what is the best case of action for upgrading our validators to a stable version of parityDB if that even exists now.

The documentation is controversial, I have seen that it's been said that parityDB got somewhat production-ready over the course of 2021. Is this true? And if so - is there a way to integrate this into substrate-3 based node, or should I make an upgrade to bleeding-edge? And if so - would that be latest master or some a fixed commit, sort of like that polkadot branch?

In my understanding migrating storage should be possible by switching validators one by one to the parityDB and re-syncing them.

Please advise if possible.

**Comment by ruseinov** [comment]
Thanks a lot for this. Yep, I will try upgrading to a monthly release.
