### ISSUE TITLE
U256 div measurement

### ISSUE THREAD

**Issue by rakita** [paritytech/parity-common#608]
Currently doing some measurements on revm and how division is done in U256.
link here: https://github.com/bluealloy/revm/issues/7#issuecomment-991956046

In short, I am getting a performance boost from ~77-80ms to ~64-66ms
by using this part of code: https://github.com/paritytech/parity-common/blob/5fe7924049f39fc6cf772605efc5c28b3ecbae78/uint/src/uint.rs#L1181-L1185

**Comment by ordian** [comment]
See #406, #478. TL;DR is the benches result were inconsistent last time we run them. Would be good to dig into this again.

**Comment by ordian** [comment]
closed by #478
