### ISSUE TITLE
Breaking Change in "ethereum-types = 0.11.0"

### ISSUE THREAD

**Issue by fredfortier** [paritytech/parity-common#618]
Using "ethereum-types = 0.11.0" suddenly requires edition2021 because its uint dependency changes (see attach diff).
![diff-ethereum-types](https://user-images.githubusercontent.com/1474114/151628533-4a18f8fb-673b-48d1-9cc0-f769e856eeee.png) I assume this isn't intentional and that this new dependency should have been scoped to "ethereum-types = 0.12".

**Comment by niklasad1** [comment]
It's intentional see https://github.com/paritytech/parity-common/pull/617#discussion_r794371758

**Comment by ordian** [comment]
@fredfortier you can downgrade `uint` if your compiler is too old: `cargo update -p uint --precise "0.9.1"`
