### ISSUE TITLE
Add impl TryFrom<&[u8]> for fixed hash to allow callers to handle errors

### ISSUE THREAD

**Issue by ddaws** [paritytech/parity-common#621]
Hey team, I'm started using the web3 Rust library that depends on the parity-common/ethereum-types package. I made a really simple mistake that resulted in a panic and it was difficult to understand what happened from the error message. I tried to deserialize some invalid hex into an address 

```rust
let my_addr = Address::from_slice("0xbC9c9AbAB72bd0a9594b706395D65D8700c3a8fa".as_bytes());
```

Of course this doesn't work because `as_bytes()` doesn't implicitly decode hex, but this panics with an unintuitive message 

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `40`,
 right: `20`', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.9.1/src/lib.rs:55:1
```

I understand that entering the wrong address is a serious offense, but I think the caller can handle it. For example, a program may accept an address from the user. The address could be incorrect and the caller should be able to handle messaging back to the user.

I propose adding an `impl TryFrom<&[u8]> for <fixed_hash_type>` so callers are free to handle the error

```rust
let my_addr = Address::try_from("0xbC9c9AbAB72bd0a9594b706395D65D8700c3a8fa".as_bytes())
    .expect("invalid bytes passed to address");
```

**Comment by niklasad1** [comment]
There is already an [FromStr impl](https://docs.rs/primitive-types/latest/primitive_types/struct.H256.html#impl-FromStr) for the `primitive-types` that you can use for you example above.

Thus, I'm not convinced that a `TryFrom` impl is required besides if you have raw bytes then you would need to convert it to `str slice` or String to use the `FromStr`.

**Comment by ddaws** [comment]
Sorry, I missed the `FromStr` impl. This does what I want and I agree, I don't think there is much value in adding the `TryFrom`. I'll close this issue. Thank for getting back to me so quick!

**Comment by benluelo** [comment]
FWIW, I was quite surprised to find that there was no `TryFrom` impl for the hash types - they're just wrappers around `[u8; N]`, I see no reason to not implement it. In my particular case, I'm not dealing directly with strings, but with arbitrary bytes in a generic context, so going through `FromStr` isn't feasible.
