### ISSUE TITLE
Signed math for primivite-types/ethereum-types?

### ISSUE THREAD

**Issue by Pzixel** [paritytech/parity-common#631]
HI. I'm using this crate for a long time and I was even a contributor in an older repo. The limitation I'm facing right now is that I need some signed I256 math but crate provides none. Is there any plans for implementing them? 

P.S. Some guide level explanation when use what crate would be really nice since now they look pretty identical

**Comment by ordian** [comment]
No plans for signed arithmetic at the moment.

As for which crate to use:
* if you needs some ethereum types, e.g. in the context of https://github.com/paritytech/frontier, use `ethereum-types`
* if you're working with substrate-based chains, use `primitive-types`
* if you need to create a custom uint type, use `uint` crate
