### ISSUE TITLE
New Release: kvdb-rocksdb

### ISSUE THREAD

**Issue by nbaztec** [paritytech/parity-common#677]
The current version of `kvdb-rocksdb:0.15.2` has a [dependency](https://crates.io/crates/kvdb-rocksdb/0.15.2/dependencies) on `rocksdb:0.18.0` which has been flagged as vulnerable via https://github.com/advisories/GHSA-xpp3-xrff-w6rh

The dependency seems to have been fixed via https://github.com/paritytech/parity-common/commit/26d712dbc401f6065250baca41663c0c8298e60a but a new release has not been made available as of yet.

**Comment by ordian** [comment]
> This is only relevant when using
rocksdb::DBWithThreadMode::open_cf_descriptors_with_ttl() with multiple
column families.

We're not using this method and hence it's not a security release for `kvdb-rocksdb`.

**Comment by jasl** [comment]
+1 another reason is rocksdb depends on `zstd` which not follows semantic versioning, 0.18.0 still use old version which will conflict with latest one

**Comment by ordian** [comment]
> +1 another reason is rocksdb depends on `zstd` which not follows semantic versioning, 0.18.0 still use old version which will conflict with latest one

Substrate doesn't use `zstd` feature of rocksdb. Even if it's enabled, it will use `snappy` compression for compatibility reasons.

**Comment by jasl** [comment]
> > +1 another reason is rocksdb depends on `zstd` which not follows semantic versioning, 0.18.0 still use old version which will conflict with latest one
> 
> Substrate doesn't use `zstd` feature of rocksdb. Even if it's enabled, it will use `snappy` compression for compatibility reasons.

But if other crate enable `zstd`, Substrate's one will enable it too, then two `zstd` conflict each other, this Cargo bad

**Comment by ordian** [comment]
> But if other crate enable zstd

why would another crate use `rocksdb` directly instead of `kvdb-rocksdb` and enable `zstd` feature of it knowing it's useless if `snappy` is also enabled?

**Comment by jasl** [comment]
> > But if other crate enable zstd
> 
> why would another crate use `rocksdb` directly instead of `kvdb-rocksdb` and enable `zstd` feature of it knowing it's useless if `snappy` is also enabled?

`zstd` is default feature of rocksdb https://github.com/rust-rocksdb/rust-rocksdb/blob/master/Cargo.toml#L23
so if you don't `default-feature=false`, it will enable by default

We're using monorepo, a blockchain-browser app use RocksDB directly for backend storage like normal web app, that's why we found the conflicts
