### ISSUE TITLE
U256 type does not support `num_traits::int::PrimInt`

### ISSUE THREAD

**Issue by gilescope** [paritytech/parity-common#714]
and so IntegerSqrt is not supported. integer-sqrt has a blanket impl for anything that supports the `num_traits::PrimInt`.

https://crates.io/crates/integer-sqrt

**Comment by ordian** [comment]
I've implemented integer_sqrt as an inherent method, because the one provided by the crate is slow
https://github.com/paritytech/parity-common/pull/554

**Comment by gilescope** [comment]
Nice - should have spotted that feature. Now I just need to get checked add / mul / div / sub supported for U256.

**Comment by gilescope** [comment]
This should cover it: https://github.com/paritytech/parity-common/pull/716
