### ISSUE TITLE
[fixed-hash] Reconsider libc crate feature support

### ISSUE THREAD

**Issue by Robbepop** [paritytech/parity-common#79]
About the macro blocks that involve operations around using libc for implementation of `PartialEq` and `Ord`.
```rust
#[cfg(all(feature = "libc", not(target_os = "unknown")))]
#[macro_export]
#[doc(hidden)]
macro_rules! impl_libc_for_fixed_hash { ... }
```

**Question:** Is this feature (using `libc` instead of `core`) actually useful and used?
**Thesis:** The compiler should be able to do this optimization by itself.

@pepyakin told in another PR [Link](https://github.com/paritytech/parity-common/pull/76#discussion_r232955860)

> hm, I was almost sure that self.as_bytes() == other.as_bytes()/self.as_bytes().cmp(other.as_bytes()) should be lowered down to memcmp.
> 
> Besides this, existence of an OS around isn't requisite for using memcmp et al since they assumed to always exists by the compiler (or rather LLVM). In wasm32-unknown-unknown they're pulled from the compiler-builtins lib.

**Todo:**

- Make some benchmarks to test the above thesis.
- If benchmarks are in favor of the compiler doing this, remove the libc feature and code surrounding it.

**Comment by ordian** [comment]
Reopening until https://github.com/rust-lang/rust/issues/69024 is resolved.

**Comment by ordian** [comment]
cc #340

**Comment by ordian** [comment]
closing as it makes no difference
https://github.com/paritytech/parity-common/pull/340#issuecomment-585770139
