### ISSUE TITLE
Is there a corresponding library in Go for Rust's primitive-types package?

### ISSUE THREAD

**Issue by qingfengzxr** [paritytech/parity-common#796]
Hello, i use the primitive-types cargo in rust grpc. Now i want to make a go client. Is there a corresponding library in Go for Rust's primitive-types package?

**Comment by ggwpez** [comment]
The only thing about Go that i know in regards to Polkadot is that this is the most advanced lib: https://github.com/centrifuge/go-substrate-rpc-client  

Either way, this is a Go question - not an issue. Please ask somewhere in the Go community.
