### ISSUE TITLE
Why are methods deprecated without providing the alternative?

### ISSUE THREAD

**Issue by thomaseizinger** [paritytech/parity-common#90]
In version 2.5 of `fixed-hash`, certain methods like `from_slice` were deprecated with the message `"unconventional API, replaced by new_from_slice in version 0.3"` but surprisingly, the method `new_from_slice` doesn't exist yet.

I am curious in what the reasoning was behind adding a deprecation (which causes a compile-time warning) and not adding the suggested method at the same time?

**Comment by dvdplm** [comment]
> not adding the suggested method at the same time?

But version 0.3 is out! The reasoning was that we wanted people to upgrade, but I hear you, we probably should have added the methods to a `0.2.6` where possible. Will keep it in mind for the future.

**Comment by Robbepop** [comment]
Ah that is a truly bad miscommunication!
Very sorry for that. Next time we communicate this intent better.

**Comment by thomaseizinger** [comment]
The real issue in our case was because `fixed-hash` is transitive dependency! So I don't get to choose which version I get but we do still use the (re-exported) types from that crate. Meaning I have a compiler warning that I can't fix :D
It is not too bad because I was able to avoid the dependency upgrade for now but I think in general, you should only deprecate a method if you also provide a solution in the same version.
